function [prms] = get_prms(varargin)

prms = {'dataSetName','cifar10',...
			 'testIter',100, 'displayIter',200,...
			 'learnPolicy','fixed','iterPerRound',500,...
			 'isSnapshot',true,'snapshotIter',[],....
			 'momentum',0.9, 'weightDecay',0.004,...
			 'deviceId',0,'solverMode','GPU',...
			 'expName','normal',...
			 'isResume',false,...
			 'lrPower',[-2 -1 0 1 2]};
prms = get_defaults(varargin,prms,true);

if isempty(prms.snapshotIter)
	prms.snapshotIter = prms.iterPerRound;
end
end
